# Generated by Django 3.2.5 on 2021-07-23 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20210723_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certify',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifies', to='study.study'),
        ),
    ]
