# Generated by Django 3.2.5 on 2021-07-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210723_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_page',
        ),
    ]
