# Generated by Django 3.2.5 on 2021-07-23 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wakeup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certify',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certify',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifies', to='wakeup.wakeup'),
        ),
        migrations.AlterField(
            model_name='wakeup',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
