# Generated by Django 3.2.5 on 2021-07-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakeup', '0002_auto_20210723_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certify',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wakeup',
            name='created',
            field=models.DateField(),
        ),
    ]
